name: cloudHashiCorp_Vault

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest
    env:
      TF_VAR_HASHICORPTOKEN: ${{ secrets.HASHICORPTOKEN }}
      timeout-minutes: 2
      TF_LOG: DEBUG  # Enable debug logging
      
    steps:
      - name: Start
        run: echo "Start"
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Terraform 
        run: |
          cd cloudHashiCorp_Vault
          echo "Current Directory:"
          pwd
          ls -la   
          echo "Env:"   
          echo $TF_VAR_HASHICORPTOKEN 
          terraform init
          terraform plan -no-color -input=false -var "HASHICORPTOKEN=${{ secrets.HASHICORPTOKEN }}"
          terraform apply -no-color -auto-approve -input=false -var "HASHICORPTOKEN=${{ secrets.HASHICORPTOKEN }}"


      # - name: Logs
      #   run: |
      #     echo ${{ steps.Terraform.outputs.stderr }}
      #     echo ${{ steps.Terraform.outputs.exitcode }}

      # - name: Stop
      #   run: |
      #     echo "Stop"
