
#- docker run -p 8200:8200 -e 'VAULT_DEV_ROOT_TOKEN_ID=dev-only-token' hashicorp/vault
name: cloudHashiCorp_Vault
on:
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest
    env:
      #TF_VAR_HASHICORPTOKEN: "dev-only-token"
      timeout-minutes: 2
      #TF_LOG: DEBUG  # Enable debug logging
      
    steps:
      - name: Start
        run: echo "Start"
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Terraform 
        run: |
          cd cloudHashiCorp_Vault
          terraform init
          terraform plan -no-color
          terraform apply -no-color -auto-approve


      # - name: Logs
      #   run: |
      #     echo ${{ steps.Terraform.outputs.stderr }}
      #     echo ${{ steps.Terraform.outputs.exitcode }}

      # - name: Stop
      #   run: |
      #     echo "Stop"
