name: cloudHashiCorp_Vault

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest
    env:
      TF_ID: ${{ secrets.hashicorpid }}
      TF_TOKEN: ${{ secrets.hashicorptoken }}
      
    steps:
      - name: Start
        run: echo "Start"
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Terraform 
        run: |
          cd cloudHashiCorp_Vault
          # terraform fmt -check
          terraform init
          terraform plan -no-color
          terraform apply -no-color -auto-approve

      # - name: Logs
      #   run: |
      #     echo ${{ steps.Terraform.outputs.stderr }}
      #     echo ${{ steps.Terraform.outputs.exitcode }}

      # - name: Stop
      #   run: |
      #     echo "Stop"
