name: createGitRepo
on: 
    workflow_dispatch:
        inputs:
            a: 
              type: string

jobs:
    job1:
       runs-on: [ubuntu-latest]
       env:
        TF_VAR_token: ${{ secrets.token }}
        TF_LOG: DEBUG
       defaults:
           run:
               working-directory: TerraformGit/

       steps:

          - name: Install Terraform
            uses: hashicorp/setup-terraform@v3
      
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name:  terraform_init
            run: |
             terraform fmt -check
             terraform init
             terraform plan -no-color
             echo ${{ steps.terraform_plan.outputs.stdinfo }}
             echo ${{ steps.terraform_plan.outputs.stderr }}
             echo ${{ steps.terraform_plan.outputs.exitcode }}
             terraform apply -no-color -auto-approve
                 

                
             

             
