name: gitSecrets
on:
  workflow_dispatch:

jobs:
    job1:
      runs-on: ubuntu-latest
      steps:
        - name: TestSecrest
          env:
            TF_VAR_TOKEN: ${{secrets.token}} #pre-fix "TF_VAR" 
          shell: python
          run: |
            import os
            print(len(os.getenv("TF_VAR_TOKEN")))
