name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Start"

      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform 
        run: |
          terraform fmt -check
          terraform init
          terraform plan
          terraform apply

      - name: Logs
        run: |
          echo ${{ steps.Terraform.outputs.stderr }}
          echo ${{ steps.Terraform.outputs.exitcode }}

      - name: Run a multi-line script
        run: |
          echo "Stop"
