name: Test2
on: 
    workflow_dispatch:
        inputs:
            a: 
              type: string



jobs:
    job1:
       runs-on: [ubuntu-latest]
       steps:

          - name: Install Terraform
            uses: hashicorp/setup-terraform@v3
      
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: Git Creation Using Terraform
            env:
              token: ${{ secrets.token }}
            working-directory: TerraformGit/

          - name: terraform fmt -check
            run:  terraform fmt -check

          - name:  terraform init
            run: terraform init

          - name: terraform plan
            run: terraform plan -no-color

          -name: terraform apply
           run: terraform apply -no-color -auto-approve
                 

                
             

             
