name: Test2
on: 
    workflow_dispatch:
        inputs:
            a: 
              type: string



jobs:
    job1:
       runs-on: [ubuntu-latest]
       defaults:
           run:
               working-directory: TerraformGit/
           env:
              token: ${{ secrets.token }}
              TF_LOG: DEBUG
       steps:

          - name: Install Terraform
            uses: hashicorp/setup-terraform@v3
      
          - name: Checkout Repo
            uses: actions/checkout@v4

            working-directory: TerraformGit/
            run:  terraform fmt -check

          - name:  terraform_init
            run: terraform init

          - name: terraform_plan
            run: terraform plan -no-color

          - name: Logs
            run: |
              echo ${{ steps.terraform_plan.outputs.stdinfo }}
              echo ${{ steps.terraform_plan.outputs.stderr }}
              echo ${{ steps.terraform_plan.outputs.exitcode }}

          - name: terraform apply
            run: terraform apply -no-color -auto-approve
                 

                
             

             
