name: testSecrets
on:
  workflow_dispatch:

jobs:
    job1:
      runs-on: ubuntu-latest
      steps:
        - name: TestSecrest
          env:
            token: ${{secrets.token}}
          shell: python
          run: |
            import os
            print(len(os.getenv("token")))
