name: Test2
on: 
    workflow_dispatch:
        inputs:
            a: 
              type: string



jobs:
    job1:
       runs-on: [ubuntu-latest]
       steps:

          - name: Install Terraform
            uses: hashicorp/setup-terraform@v3
      
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: Git Creation Using Terraform
            env:
              token: ${{ secrets.token }}
            working-directory: TerraformGit/
            run: |
                  terraform fmt -check
                  terraform init
                  terraform plan -no-color
                  terraform apply -no-color -auto-approve
                  echo ${{inputs.a}}
             

             
