name: testSecrets
on:
  workflow_dispatch:

jobs:
  runs-on: ubuntu-latest
  job1:
    name: TestSecrest
    env:
      token: ${{secrets.token}}
    shell: python
    run: |
    import os
    print(len(os.getenv("token")))
